parameters:
    pledg_payment.method.identifier_prefix.pledg: 'pledg'
services:
    _defaults:
        public: false
        autowire: true

    Pledg\Bundle\PaymentBundle\Factory\ReferenceFactoryInterface: '@Pledg\Bundle\PaymentBundle\Factory\ReferenceFactory'
    Pledg\Bundle\PaymentBundle\JWT\HandlerInterface: '@Pledg\Bundle\PaymentBundle\JWT\HS256Handler'
    Pledg\Bundle\PaymentBundle\Method\Config\Factory\PledgConfigFactoryInterface : '@Pledg\Bundle\PaymentBundle\Method\Config\Factory\PledgConfigFactory'
    Pledg\Bundle\PaymentBundle\Method\Config\Provider\PledgConfigProviderInterface: '@Pledg\Bundle\PaymentBundle\Method\Config\Provider\PledgConfigProvider'
    Pledg\Bundle\PaymentBundle\Method\View\Factory\PledgViewFactoryInterface: '@Pledg\Bundle\PaymentBundle\Method\View\Factory\PledgViewFactory'
    Pledg\Bundle\PaymentBundle\Method\Factory\PledgPaymentMethodFactoryInterface: '@Pledg\Bundle\PaymentBundle\Method\Factory\PledgPaymentMethodFactory'
    Pledg\Bundle\PaymentBundle\Notification\Validator\ValidatorInterface: '@Pledg\Bundle\PaymentBundle\Notification\Validator\StandardValidator'
    Pledg\Bundle\PaymentBundle\Provider\OrderProviderInterface: '@Pledg\Bundle\PaymentBundle\Provider\OrderProvider'
    Pledg\Bundle\PaymentBundle\Provider\PaymentTransactionProviderInterface: '@Pledg\Bundle\PaymentBundle\Provider\PaymentTransactionProvider'
    Pledg\Bundle\PaymentBundle\RedirectUrl\ParametersFactoryInterface: '@Pledg\Bundle\PaymentBundle\RedirectUrl\ParametersFactory'

    pledg_payment.generator.pledg_config_identifier:
        class: Oro\Bundle\IntegrationBundle\Generator\Prefixed\PrefixedIntegrationIdentifierGenerator
        public: true
        arguments:
            - '%pledg_payment.method.identifier_prefix.pledg%'

    pledg_payment.event_listener.callback.check_callback_relevance:
        class: 'Oro\Bundle\PaymentBundle\EventListener\Callback\CheckCallbackRelevanceListener'
        lazy: true
        arguments:
            - '@Pledg\Bundle\PaymentBundle\Method\Provider\PledgMethodProvider'
            - '@oro_payment.provider.payment_status'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: kernel.event_listener, event: oro_payment.callback.return, method: onReturn, priority: 20 }
            - { name: kernel.event_listener, event: oro_payment.callback.error, method: onError, priority: 20 }

    Pledg\Bundle\PaymentBundle\EventListener\Callback\PledgListener:
        lazy: true
        arguments:
            $paymentMethodProvider: '@Pledg\Bundle\PaymentBundle\Method\Provider\PledgMethodProvider'
        tags:
            - { name: kernel.event_listener, event: oro_payment.callback.return, method: onReturn }
            - { name: kernel.event_listener, event: oro_payment.callback.notify, method: onNotify }
            - { name: kernel.event_listener, event: oro_payment.callback.error, method: onError }

    Pledg\Bundle\PaymentBundle\Factory\ReferenceFactory: ~

    Pledg\Bundle\PaymentBundle\Integration\PledgChannelType:
        public: true
        tags:
            - { name: oro_integration.channel, type: pledg }

    Pledg\Bundle\PaymentBundle\JWT\HS256Handler: ~

    Pledg\Bundle\PaymentBundle\Integration\PledgTransport:
        tags:
            - { name: oro_integration.transport, type: pledg, channel_type: pledg }

    Pledg\Bundle\PaymentBundle\Method\Config\Factory\PledgConfigFactory:
        arguments:
            - '@oro_locale.helper.localization'
            - '@pledg_payment.generator.pledg_config_identifier'

    Pledg\Bundle\PaymentBundle\Method\Config\Provider\PledgConfigProvider: ~
    Pledg\Bundle\PaymentBundle\Method\View\Factory\PledgViewFactory: ~

    Pledg\Bundle\PaymentBundle\Method\View\Provider\PledgViewProvider:
        tags:
            - { name: oro_payment.payment_method_view_provider }

    Pledg\Bundle\PaymentBundle\Method\Factory\PledgPaymentMethodFactory: ~

    Pledg\Bundle\PaymentBundle\Notification\Validator\StandardValidator: ~

    Pledg\Bundle\PaymentBundle\Method\Provider\PledgMethodProvider:
        tags:
            - { name: oro_payment.payment_method_provider }

    Pledg\Bundle\PaymentBundle\Provider\OrderProvider: ~

    Pledg\Bundle\PaymentBundle\Provider\PaymentTransactionProvider:
        arguments:
            $repository: '@oro_payment.repository.payment_transaction'

    Pledg\Bundle\PaymentBundle\RedirectUrl\ParametersFactory: ~
