parameters:
    pledg_payment.method.identifier_prefix.pledg: 'pledg'
services:
    _defaults:
        public: false

    pledg_payment.generator.pledg_config_identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%pledg_payment.method.identifier_prefix.pledg%'

    pledg_payment.integration.channel: '@Pledg\Bundle\PaymentBundle\Integration\PledgChannelType'
    pledg_payment.integration.transport: '@Pledg\Bundle\PaymentBundle\Integration\PledgTransport'
    pledg_payment.factory.pledg_config: '@Pledg\Bundle\PaymentBundle\PaymentMethod\Config\Factory\PledgConfigFactory'
    pledg_payment.payment_method.config.provider: '@Pledg\Bundle\PaymentBundle\PaymentMethod\Config\Provider\PledgConfigProvider'
    pledg_payment.factory.method_view.pledg: '@Pledg\Bundle\PaymentBundle\PaymentMethod\View\Factory\PledgViewFactory'
    pledg_payment.payment_method_view_provider.pledg: '@Pledg\Bundle\PaymentBundle\PaymentMethod\View\Provider\PledgViewProvider'
    pledg_payment.factory.method.pledg: '@Pledg\Bundle\PaymentBundle\PaymentMethod\Factory\PledgPaymentMethodFactory'
    pldg_payment.payment_method_provider.pledg: '@Pledg\Bundle\PaymentBundle\PaymentMethod\Provider\PledgMethodProvider'

    Pledg\Bundle\PaymentBundle\Integration\PledgChannelType:
        public: true
        tags:
            - { name: oro_integration.channel, type: pledg }

    Pledg\Bundle\PaymentBundle\Integration\PledgTransport:
        tags:
            - { name: oro_integration.transport, type: pledg, channel_type: pledg }

    Pledg\Bundle\PaymentBundle\PaymentMethod\Config\Factory\PledgConfigFactory:
        public: false
        arguments:
            - '@oro_locale.helper.localization'
            - '@pledg_payment.generator.pledg_config_identifier'

    Pledg\Bundle\PaymentBundle\PaymentMethod\Config\Provider\PledgConfigProvider:
        arguments:
            - '@doctrine'
            - '@logger'
            - '@pledg_payment.factory.pledg_config'

    Pledg\Bundle\PaymentBundle\PaymentMethod\View\Factory\PledgViewFactory:
        public: false

    Pledg\Bundle\PaymentBundle\PaymentMethod\View\Provider\PledgViewProvider:
        public: false
        arguments:
            - '@pledg_payment.payment_method.config.provider'
            - '@pledg_payment.factory.method_view.pledg'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    Pledg\Bundle\PaymentBundle\PaymentMethod\Factory\PledgPaymentMethodFactory:
        public: false

    Pledg\Bundle\PaymentBundle\PaymentMethod\Provider\PledgMethodProvider:
        public: false
        arguments:
            - '@pledg_payment.payment_method.config.provider'
            - '@pledg_payment.factory.method.pledg'
        tags:
            - { name: oro_payment.payment_method_provider }
